In [1]:
import pandas as pd
from glob import glob

In [2]:
filepaths = glob(r'C:\Users\ryout\Documents\jupyterlab\excel\python\*.xls')
filepaths

['C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_4年1組_2学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_4年2組_2学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_4年3組_2学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_4年4組_2学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_5年1組_1学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_5年1組_2学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_5年2組_1学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_5年2組_2学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_5年3組_1学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_5年3組_2学期_所見.xls',
 'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_5年4組_1学期_所見.xls']

In [3]:
filepath = filepaths[0]

In [4]:
filepath

'C:\\Users\\ryout\\Documents\\jupyterlab\\excel\\python\\所見_4年1組_2学期_所見.xls'

In [5]:
_df = pd.read_excel(filepath)
_df

,生徒管理コード,学年,組,番号,氏名,所見
0,20190002,4年,1組,1,青木 柊羽,たくさんの友達と校庭で楽しく遊ぶ姿多く見られるようになりました。遊びを通して、授業でも友達...
1,20190029,4年,1組,2,新井 美七翔,２学期は、おにごっことけいどろで夢中になって遊んでいます。遊びの中でリーダーシップを発揮し...
2,20190031,4年,1組,3,石倉 伊織,友達の輪に入り、楽しく遊ぶ姿が微笑ましく思います。遊びを通して、友達との関わり方やルールに...
3,20190005,4年,1組,4,伊地知 勇一,友達と仲良く校庭で遊ぶ姿が印象的です。遊びを通して、ルールを守り楽しく生活するために必要な...
4,20200093,4年,1組,5,猪股 楓,NaN
5,20190008,4年,1組,6,扇田 龍成,休み時間のおにごっこを誰よりも楽しみにしています。遊びであっても、闇雲に逃げるのはなく作戦...
6,20190010,4年,1組,7,川辺 静雅,自分のできることを考え、目標をもって元気に生活することができました。また、自分の気持ちや考...
7,20190090,4年,1組,8,上林 にこ,多くの友達と校庭で楽しく遊ぶ姿が見られるようになりました。これまでと異なる友達との遊びを通...
8,20190091,4年,1組,9,木村 心晴,２学期は進んで外に出て遊ぶ姿が見られました。遊びを通して友達との交流が増え、うれしく思いま...
9,20190060,4年,1組,10,工藤 夏愛,おにごっこを楽しそうに遊ぶ姿が印象的で、遊びを通して友達との交流が増え、うれしく思います。...
10,20190038,4年,1組,11,小名 健太,２学期も毎日元気に過ごし、授業では積極的に発言をして意欲的に生活することができました。体育...
11,20210079,4年,1組,12, 伊織,毎日校庭で元気よく遊んでいます。特に、けいどろでは「警察役」となり、楽しそう友達を追いかけ...
12,20190013,4年,1組,13,篠部 大珠,友達との交流が増え、休み時間に一緒におにごっこをする姿が見られるようになりました。体育「テ...
13,20190064,4年,1組,14,澁澤 蘭菜,学級のおにごっこに混ざり遊ぶ姿が見られるようになり、授業中の友達との交流も増えてきました。...
14,20190043,4年,1組,15,菅谷 心咲,２学期は、多くの友達との交流を通して学ぶ姿が見られるようになりました。休み時間は進んで外で...
15,20190097,4年,1組,16,杉江 杏花,毎日の外遊びを楽しみにしている姿が印象的です。おにごっこを通して多くの友達と交流し、笑い声...
16,20190020,4年,1組,17,筑比地 胡桃,２学期は進んで外に出て遊ぶ姿が見られました。遊びを通して関わる友達が増えたことで、授業中の...
17,20190069,4年,1組,18,橋本 陽向,休み時間は、学級の友達と仲良く遊ぶ様子が印象的です。特に、遊びを決める際に話合いの中心に立...
18,20190071,4年,1組,19,林 陽菜乃,２学期は進んで外に出て遊ぶ姿が見られました。遊びを通して関わる友達が増えたことで、授業中の...
19,20190072,4年,1組,20,原田 真由美,自分の気持ちや考えを表現する力がすばらしいと思います。その言葉が相手にどのように伝わるのか...
20,20190051,4年,1組,21,原田 美月,休む時間は、進んで校庭に出て遊ぶ姿が印象的です。おにごっこをきっかけに自分から声をかけて多...
21,20190104,4年,1組,22,半田 紗都,２学期は進んで外に出て遊ぶ姿が見られました。遊びを通して友達との交流が増え、うれしく思いま...
22,20190105,4年,1組,23,藤原 拓真,多くの友達と校庭で楽しく遊ぶ姿が見られるようになり、進んで「おに」に手を挙げるなど、少しず...
23,20190025,4年,1組,24,細谷 佳樹,２学期もリーダーシップを発揮し、校庭で楽しく遊ぶ姿が印象的でした。短い時間で、意見をとりま...
24,20190074,4年,1組,25,堀井 愛奈,毎日、休み時間のおにごっこやけいどろを楽しみにしており、友達を誘って校庭に出ていく姿が微笑...
25,20190054,4年,1組,26,山田 和合,授業や遊びを通して、交友関係を広げました。多くの友達と交流することで、様々な考えにふれ学び...
26,20190027,4年,1組,27,山本 頼輝,２学期は進んで外に出て遊ぶ姿が見られました。遊びを通して友達との交流が増え、うれしく思いま...
27,20190019,4年,1組,28,滝澤 星乃花,２学期は、毎日外で元気におにごっこやけいどろをしており、遊びを通して友達の輪を広げることが...

In [6]:
df = _df.iloc[:, [1,4,5]]

In [7]:
def extract(filepath):
    _df = pd.read_excel(filepath)
    df = _df.iloc[:, [1,2,4,5]]
    return df

In [8]:
df = extract(filepath)
df.head()

   学年   組      氏名                                                 所見
0  4年  1組   青木 柊羽  　たくさんの友達と校庭で楽しく遊ぶ姿多く見られるようになりました。遊びを通して、授業でも友達...
1  4年  1組  新井 美七翔  　２学期は、おにごっことけいどろで夢中になって遊んでいます。遊びの中でリーダーシップを発揮し...
2  4年  1組   石倉 伊織  　友達の輪に入り、楽しく遊ぶ姿が微笑ましく思います。遊びを通して、友達との関わり方やルールに...
3  4年  1組  伊地知 勇一  　友達と仲良く校庭で遊ぶ姿が印象的です。遊びを通して、ルールを守り楽しく生活するために必要な...
4  4年  1組    猪股 楓                                                NaN

In [9]:
df = pd.DataFrame()

for filepath in filepaths:
    _df = extract(filepath)
    df = pd.concat([df,_df])

In [10]:
df

    学年   組      氏名                                                 所見
0   4年  1組   青木 柊羽  　たくさんの友達と校庭で楽しく遊ぶ姿多く見られるようになりました。遊びを通して、授業でも友達...
1   4年  1組  新井 美七翔  　２学期は、おにごっことけいどろで夢中になって遊んでいます。遊びの中でリーダーシップを発揮し...
2   4年  1組   石倉 伊織  　友達の輪に入り、楽しく遊ぶ姿が微笑ましく思います。遊びを通して、友達との関わり方やルールに...
3   4年  1組  伊地知 勇一  　友達と仲良く校庭で遊ぶ姿が印象的です。遊びを通して、ルールを守り楽しく生活するために必要な...
4   4年  1組    猪股 楓                                                NaN
..  ..  ..     ...                                                ...
23  5年  4組   原田 美月  　いつも笑顔で友達と関われる美月さんは、休み時間になると仲間と一緒におにごっこやだるまさんが...
24  5年  4組   半田 紗都  　いつも元気に学校生活を送る紗都さんは、自分から友達の輪に入り、みんなが楽しくなるよう笑顔で...
25  5年  4組   樋渡 心結  　元気に学校生活を送る心結さんは、自分から友達の輪に入り、学級レクも楽しんでいました。社会科...
26  5年  4組   渡邊 來輝  　友達や先生に笑顔で話しかける來輝さんは、休み時間になるとボール遊びやおにごっこを友達と一緒...
27  5年  4組   岡田 青空  　休み時間には、学年の友達と元気に体を動かして外遊びをしていました。クラブ活動では、パソコン...

[320 rows x 4 columns]

In [11]:
df = df.dropna()

In [12]:
df

    学年   組      氏名                                                 所見
0   4年  1組   青木 柊羽  　たくさんの友達と校庭で楽しく遊ぶ姿多く見られるようになりました。遊びを通して、授業でも友達...
1   4年  1組  新井 美七翔  　２学期は、おにごっことけいどろで夢中になって遊んでいます。遊びの中でリーダーシップを発揮し...
2   4年  1組   石倉 伊織  　友達の輪に入り、楽しく遊ぶ姿が微笑ましく思います。遊びを通して、友達との関わり方やルールに...
3   4年  1組  伊地知 勇一  　友達と仲良く校庭で遊ぶ姿が印象的です。遊びを通して、ルールを守り楽しく生活するために必要な...
5   4年  1組   扇田 龍成  　休み時間のおにごっこを誰よりも楽しみにしています。遊びであっても、闇雲に逃げるのはなく作戦...
..  ..  ..     ...                                                ...
23  5年  4組   原田 美月  　いつも笑顔で友達と関われる美月さんは、休み時間になると仲間と一緒におにごっこやだるまさんが...
24  5年  4組   半田 紗都  　いつも元気に学校生活を送る紗都さんは、自分から友達の輪に入り、みんなが楽しくなるよう笑顔で...
25  5年  4組   樋渡 心結  　元気に学校生活を送る心結さんは、自分から友達の輪に入り、学級レクも楽しんでいました。社会科...
26  5年  4組   渡邊 來輝  　友達や先生に笑顔で話しかける來輝さんは、休み時間になるとボール遊びやおにごっこを友達と一緒...
27  5年  4組   岡田 青空  　休み時間には、学年の友達と元気に体を動かして外遊びをしていました。クラブ活動では、パソコン...

[314 rows x 4 columns]

In [13]:
df.to_excel(r'C:\Users\ryout\Documents\jupyterlab\excel\all_data.xlsx', index=False)